"""Add settings JSON to Project

Revision ID: 8140ff54b4d1
Revises: 73e63f71d8cb
Create Date: 2026-08-01 16:14:23.264091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8140ff54b4d1'
down_revision: Union[str, Sequence[str], None] = '73e63f71d8cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('settings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'settings')
    # ### end Alembic commands ###
